- name: Configure reddit-db
  hosts: db
  vars:
    db_bind_ip: "{{ ansible_default_ipv4.address }}"
  become: true # <-- Выполнить задание от root
  tasks:
  - name: Change mongo config file
    template:
      src: templates/mongod.conf.j2 # <-- Путь до локального файла-шаблона
      dest: /etc/mongod.conf # <-- Путь на удаленном хосте
      mode: 0644 # <-- Права на файл, которые нужно установить
      backup: yes
    notify: restart mongod
  handlers:
  - name: restart mongod
    service: name=mongod state=restarted
