---
# Один playbook, один сценарий
- name: Configure hosts & deploy application # <-- Словесное описание сценария (name)
  hosts: all # <-- Для каких хостов будут выполняться описанные ниже таски (hosts)
  tasks: # <-- Блок тасков (заданий), которые будут выполняться для данных хостов
  - debug:
      msg: >
        System {{ inventory_hostname }} has address {{ ansible_default_ipv4.address }},
        reddit-db has {{ hostvars['reddit-db']['ansible_facts']['default_ipv4']['address'] }} internal address.
    when: ansible_default_ipv4.gateway is defined
    tags: debug
  - name: Add unit file for Puma
    become: true
    copy:
      src: files/puma.service
      dest: /etc/systemd/system/puma.service
    notify: reload puma
    tags: app
  - name: Add config for DB connection
    vars:
      db_host_ip: "{{ hostvars['reddit-db']['ansible_facts']['default_ipv4']['address'] }}"
    template:
      src: templates/db_config.j2
      dest: /home/appuser/db_config
    tags: app
  - name: enable puma
    become: true
    systemd: name=puma enabled=yes
    tags: app
  - name: Fetch the latest version of application code
    git:
      repo: "https://github.com/express42/reddit.git"
      dest: /home/appuser/reddit
      version: monolith # <-- Указываем нужную ветку
    tags: deploy
    notify: reload puma
  - name: Bundle install
    bundler:
      state: present
      chdir: /home/appuser/reddit # <-- В какой директории выполнить команду bundle
    tags: deploy
  - name: Change mongo config file
    become: true # <-- Выполнить задание от root
    vars:
      db_bind_ip: "{{ ansible_default_ipv4.address }}"
    template:
      src: templates/mongod.conf.j2 # <-- Путь до локального файла-шаблона
      dest: /etc/mongod.conf # <-- Путь на удаленном хосте
      mode: 0644 # <-- Права на файл, которые нужно установить
      backup: yes
    notify: restart mongod
    tags: db # <-- Список тэгов для задачи
  handlers: # <-- Добавим блок handlers и задачу
  - name: reload puma
    become: true
    systemd: name=puma state=restarted
  - name: restart mongod
    become: true
    service: name=mongod state=restarted
